//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int Id { get; set; }
        public int Id_good { get; set; }
        public int Id_cashheading { get; set; }
    
        public virtual CashHeading CashHeading { get; set; }
        public virtual Good Good { get; set; }
    }
}
