//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.CashHeading = new HashSet<CashHeading>();
        }
    
        public int Id { get; set; }
        public string Shop1 { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<CashHeading> CashHeading { get; set; }
    }
}
